"""Frozen constants for the synthetic-only E0R1 identifiability audit."""

OBJECTIVE_GRADIENT_TOLERANCE = 1e-8
PINV_TRAIN_RMSE_TOLERANCE = 1e-6
PINV_PRIMARY_RCOND = 1e-10
PINV_SENSITIVITY_RCONDS = (1e-8, 1e-6)
CORRECT_CI_THRESHOLD = 0.80
CI_INCREMENT_THRESHOLD = 0.10
PERMUTATION_TOLERANCE = 1e-6
DERANGEMENT_IDENTITY_THRESHOLD = 0.40

LBFGS_MAX_ITERATIONS = 500
LBFGS_HISTORY_SIZE = 100
LBFGS_TOLERANCE_GRAD = 1e-10
LBFGS_TOLERANCE_CHANGE = 1e-12
SOLVER_RELATIVE_GRADIENT_TOLERANCE = 1e-8
