"""Frozen contract for the synthetic-only E0R2 proposal triage."""

STAGE = "P1R2B-E0R2_PROPOSAL_NUMERICAL_CLOSURE"
PRIMARY_RCOND = 1e-10
HUBER_DELTA = 1.0
TRAIN_RMSE_TOLERANCE = 1e-6
FULL_GRADIENT_TOLERANCE = 1e-8
OBJECTIVE_TOLERANCE = 1e-12

